Bail out on bad build config

diff --git a/bin/mozconfig b/bin/mozconfig
--- a/bin/mozconfig
+++ b/bin/mozconfig
@@ -1,8 +1,20 @@
 include() {
   log include "$1"
+  OLDPREFIX=$PREFIX
+  PREFIX="${PREFIX}  "
   if [ -f $1 ]; then
     . $1
   fi
+  PREFIX=$OLDPREFIX
+}
+
+must_include() {
+  if [ ! -f $1 ]; then
+    echo "Missing include $1"
+    exit 1
+  fi
+
+  include $1
 }
 
 CONFIG=$BUILD_BASE/config
@@ -29,6 +41,8 @@ if [ "$BUILD_CHANNEL" != "default" ]; then
 fi
 
 include $CONFIG/mozconfig
+must_include $CONFIG/levels/$BUILD_LEVEL.mozconfig
+must_include $CONFIG/types/$BUILD_TYPE.mozconfig
 include $CONFIG/apps/$BUILD_APP.mozconfig
 include $CONFIG/channels/$BUILD_CHANNEL.mozconfig
 include $CONFIG/platforms/$BUILD_PLATFORM.mozconfig
